package gstekyc.tml.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5.fuse.jdk11-800013
 * 2020-01-10T17:30:30.436+05:30
 * Generated source version: 3.3.5.fuse.jdk11-800013
 *
 */
@WebServiceClient(name = "GSTwsdl",
                  wsdlLocation = "file:/C:/Users/swapnalitoraskar.ttl/workspace/prjTML_GSTeKYC/src/main/resources/GSTwsdl.wsdl",
                  targetNamespace = "http://service.TML.GSTeKYC/")
public class GSTwsdl_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.TML.GSTeKYC/", "GSTwsdl");
    public final static QName GSTwsdlPort = new QName("http://service.TML.GSTeKYC/", "GSTwsdlPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/swapnalitoraskar.ttl/workspace/prjTML_GSTeKYC/src/main/resources/GSTwsdl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GSTwsdl_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/swapnalitoraskar.ttl/workspace/prjTML_GSTeKYC/src/main/resources/GSTwsdl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GSTwsdl_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GSTwsdl_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GSTwsdl_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GSTwsdl_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GSTwsdl_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GSTwsdl_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GSTwsdl
     */
    @WebEndpoint(name = "GSTwsdlPort")
    public GSTwsdl getGSTwsdlPort() {
        return super.getPort(GSTwsdlPort, GSTwsdl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GSTwsdl
     */
    @WebEndpoint(name = "GSTwsdlPort")
    public GSTwsdl getGSTwsdlPort(WebServiceFeature... features) {
        return super.getPort(GSTwsdlPort, GSTwsdl.class, features);
    }

}
