package gstekyc.tml.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5.fuse.jdk11-800013
 * 2020-01-10T17:30:30.385+05:30
 * Generated source version: 3.3.5.fuse.jdk11-800013
 *
 */
@WebService(targetNamespace = "http://service.TML.GSTeKYC/", name = "GSTwsdl")
@XmlSeeAlso({ObjectFactory.class})
public interface GSTwsdl {

    @WebMethod(operationName = "GSTRequest")
    @RequestWrapper(localName = "GSTRequest", targetNamespace = "http://service.TML.GSTeKYC/", className = "gstekyc.tml.service.GSTRequestObject")
    @ResponseWrapper(localName = "GSTResponse", targetNamespace = "http://service.TML.GSTeKYC/", className = "gstekyc.tml.service.GSTResponseObject")
    public void gstRequest(

        @WebParam(name = "consent", targetNamespace = "")
        java.lang.String consent,
        @WebParam(name = "gstin", targetNamespace = "")
        java.lang.String gstin,
        @WebParam(name = "name1", targetNamespace = "")
        java.lang.String name1,
        @WebParam(mode = WebParam.Mode.OUT, name = "KYC", targetNamespace = "")
        javax.xml.ws.Holder<KYCObject> kyc,
        @WebParam(mode = WebParam.Mode.OUT, name = "NameMatch", targetNamespace = "")
        javax.xml.ws.Holder<NameMatchObject> nameMatch
    );
}
